### ISSUE TITLE
Change of maintainer

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#106]
I won't be able to maintain this package any more due to other development responsibilities that should take priority, so I would prefer if someone else took over as a maintainer and kept the active development going.

If nobody wants to, I can archive the package on CRAN, and someone else can maintain it only on GitHub, just like _ospsuite_ and _tlf_. If someone can, I would be happy to walk them through the CRAN submission process.

**Comment by msevestre** [comment]
That's too bad. 
My 2 cents would be to implement the same structure as all other packages that we have (e.g. we do not really need CRAN submission as this package is really oriented towards our needs)

**Comment by IndrajeetPatil** [comment]
> we do not really need CRAN submission as this package is really oriented towards our needs

Yeah, agreed. I will wait until the end of this week for the others to chime in. Barring no objections, I will archive it.

Feel free to change the `DESCRIPTION` if you can maintain it.
