### ISSUE TITLE
Make `1.3.0` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#109]
We are using this version throughout the ecosystem now, so would be good to make this release soon.

**Comment by Yuri05** [comment]
Pre-Release created: https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/releases/tag/v1.3.17

**Comment by IndrajeetPatil** [comment]
Thanks, Yuri!

Btw, do we really need to include "What has changed" section in the release notes?

I think the other details are already quite comprehensive, and this section is redundant.

**Comment by Yuri05** [comment]
you mean the automatically created full log? probably not. Removed :)
