### ISSUE TITLE
`toObjectType()` out of scope?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#12]
We had agreed to not include any R functions that deal with `.NET` code in this package, so I think the following function is out of scope.

https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/blob/5bfdff63c18a0fbb47bff00a3b6832c5555c7806/R/utilities.R#L11-L18

Realized this while trying to write tests for it.

Do you agree, @msevestre?

**Comment by msevestre** [comment]
Yep. Remove
