### ISSUE TITLE
R CMD checks fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by rengelke** [Open-Systems-Pharmacology/OSPSuite.RUtils#142]
R CMD checks fail on Ubuntu 18.04 due to Unsupported GitHub Actions Environment.

As of now, GitHub Actions supports Ubuntu versions 20.04 and 22.04 as you can find [here](https://github.com/actions/runner-images).

@Yuri05, @Felixmil Should this be updated OR should we move to GitHub actions workflows in the [Workflows repository](https://github.com/Open-Systems-Pharmacology/Workflows)?

**Comment by Yuri05** [comment]
I would simply replace `ubuntu-18.04` with `ubuntu-22.04` in the action.
After the switch from rClr to rSharp we will not support 18.04 anyway.
