### ISSUE TITLE
remove testing on AppVeyor?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#15]
@msevestre  We are using GHA for computing code coverage, for R CMD check, and for building the website.
So using AppVeyor is not necessary any more.

Can I remove all relevant infrastructure from this repo (yaml file, rake files, git submodule, etc.)?

**Comment by msevestre** [comment]
why are we using appvyeor for then?

**Comment by msevestre** [comment]
and so you have found a way to build the package? how is the version defined?

**Comment by msevestre** [comment]
we should add the lint GHA to all our packages as one check

**Comment by IndrajeetPatil** [comment]
We don't use AppVeyor for this repo, so this is not relevant any more. 

> we should add the lint GHA to all our packages as one check

Done for this repo.
