### ISSUE TITLE
Package version should be independent from ospsuite-R version

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.RUtils#17]
Right now it's 10.0.72
It should be 1.0.0 and increase from there

How is the build number increased with GA?

**Comment by IndrajeetPatil** [comment]
Dang it!

I thought we wanted all package versions to be in sync. I have already submitted to CRAN, but, when it comes back for resubmission, I will change the version.

**Comment by msevestre** [comment]
Nope I don't think this makes sense. There is no reason to always update the version of rutils with each new version of the suite. If you look at all our components, they all have different versions (especially the build version, z in x.y.z). Mobi, pksim, ospsuite.core and R, installation.validator and suite have the same 10.0 version because they are released at the same time... always

**Comment by IndrajeetPatil** [comment]
Yeah, that makes sense. 

> How is the build number increased with GA?

GHA doesn't change the build number. But note that we actually don't need to do this any more, since each CRAN release will be accompanied by a binary on CRAN, and we will be using these binaries in our other packages in the ecosystem. Does that make sense?

**Comment by msevestre** [comment]
> Does that make sense?

No How do you know the version of the binaries? OR do you always have to change it by HAND before committing (I can't believe this would be the workflow)
Or can you submit two packages with the same version on CRAN (this would be a reason enough to never use cran again if this were the case :))

**Comment by IndrajeetPatil** [comment]
> OR do you always have to change it by HAND before committing 

Yes, you decide the version while submitting to CRAN. I personally follow [Haskell Package Versioning Policy](https://pvp.haskell.org/).

For example, for my package `{ggstatsplot}`, you can see the [archive ](https://cran.r-project.org/src/contrib/Archive/ggstatsplot/) of all prior releases. So, if you needed a particular version, you will grab binaries for that version from this archive. You can find such archive for every package that ever existed on CRAN.

> Or can you submit two packages with the same version on CRAN

CRAN has 18,000 packages and has been doing this for over 20 years and thought about pretty much all possible issues that can arise. And, no, you **can't** submit the same package twice with the same version.

**Comment by msevestre** [comment]
>Yes, you decide the version while submitting to CRAN

So this is done by hand? Maybe you can work us through the flow on Wednesday? I think we should use a version policy that is compatible with semantic versioning. This is maybe what Haskell is doing. No idea

**Comment by msevestre** [comment]
>this would be a reason enough to never use cran again if this were the case :)

This was a joke BTW.

**Comment by IndrajeetPatil** [comment]
![image](https://user-images.githubusercontent.com/11330453/143930630-a48b7a89-3298-4251-973d-1dc8329f02bf.png)

**Comment by IndrajeetPatil** [comment]
Closing because the version is now `1.0.0`.

I will open a separate issue about auto-incrementing version with GHA.
