### ISSUE TITLE
Separate documentation for different kinds of `validate*()` functions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#19]
`??validateIsSameLength` leads to help page of `ospsuite.utils::validateIsOfType	`

![image](https://user-images.githubusercontent.com/25903040/149161579-4c68ae65-7d44-4a65-8ad9-c059140354b8.png)

**Comment by IndrajeetPatil** [comment]
This is to be expected. All validation helpers share the same `.Rd` file because they are closely related to each other. 

For the same reason, all of them are listed on the same webpage on the website:
https://www.open-systems-pharmacology.org/OSPSuite.RUtils/reference/validateIsOfType.html

Why are you calling `??validateIsSameLength`, and not `?validateIsSameLength`?

**Comment by IndrajeetPatil** [comment]
Oh, you also need to load `library(ospsuite.utils)` for `?validateIsSameLength` to work.

Once the `DataCombined` PR is merged, you won't need to do `library(ospsuite.utils)`, ospsuite would internally load all these functions.

**Comment by PavelBal** [comment]
> This is to be expected. All validation helpers share the same .Rd file because they are closely related to each other.

`validateIsSameLength` does something completely different than `validateIsOfType` and has other arguments. "Check if the provided object is of certain type" is definitely NOT what `validateIsSameLength` does.

**Comment by IndrajeetPatil** [comment]
> validateIsSameLength does something completely different than validateIsOfType and has other arguments

Good point. I will move it out of that particular `.Rd` file, but others should continue to share the same `.Rd` file since they are under the umbrella of `validateIsOfType()`.

**Comment by IndrajeetPatil** [comment]
BTW, I can't seem to figure out what `objectName` does here:

``` r
ospsuite.utils::validateIsSameLength
#> function(...) {
#>   if (isSameLength(...)) {
#>     return()
#>   }
#> 
#>   # Name of the variable in the calling function
#>   objectName <- deparse(substitute(list(...)))
#> 
#>   # Name of the arguments
#>   argnames <- sys.call()
#>   arguments <- paste(lapply(argnames[-1], as.character), collapse = ", ")
#> 
#>   stop(messages$errorDifferentLength(arguments))
#> }
#> <bytecode: 0x0000000024352b50>
#> <environment: namespace:ospsuite.utils>
```

<sup>Created on 2022-01-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Is it needed for this function to work? (cc @msevestre)

**Comment by msevestre** [comment]
I don't think so. It was probably used at some point and refactored out and left. That would be a serious side effects it a variable not used was required for the rest of the function to work

ME : DELETE!!

**Comment by PavelBal** [comment]
Delete.

**Comment by IndrajeetPatil** [comment]
For the new division of this function family documentation, see:
https://www.open-systems-pharmacology.org/OSPSuite.RUtils/reference/index.html#validation-helpers
