### ISSUE TITLE
Make `develop` the default branch

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#26]

**Comment by IndrajeetPatil** [comment]
Duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/3

**Comment by PavelBal** [comment]
@msevestre I have created the branch. Please change the settings.

**Comment by msevestre** [comment]
Will do as soon as all our PR are merged. Otherwise this is going to be a mess

**Comment by IndrajeetPatil** [comment]
No more pending PRs for now, so feel free to do this change.

**Comment by msevestre** [comment]
done
