### ISSUE TITLE
rename `getEnumKey` to `enumGetKey`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#28]
All other `enum` functions follow the naming patter `enumXXXX`, this is the only one that does not. This would be a breaking change but I do not think many users have used this so far.

Should be checked in `ospsuite-r`, reporting engine.

@msevestre @pchelle What do you think.

**Comment by pchelle** [comment]
Could we use the same aliasing strategy implemented between `validateIsString` and `validateIsCharacter` here ?

**Comment by IndrajeetPatil** [comment]
`ospsuite.utils::enumGetKey` now masks `esqlabsR::enumGetKey`:
https://esqlabs.github.io/esqlabsR/reference/enumGetKey.html

Should the latter be removed in favor of the former?
