### ISSUE TITLE
`isIncluded` for all data types?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#29]
Following from the documentation of the function `isIncluded` it is not clear to me, which data types are supported. Probably only atomic, and it cannot check whether e.g. a certain `DataSet` is inside a list of `DataSet`? In this case, it should be documented accordingly.

**Comment by PavelBal** [comment]
```
> isIncluded(c(1,2,3), list(c(1,2,3)))
[1] FALSE
```

So definitely only for atomics...

**Comment by PavelBal** [comment]
```
> isIncluded(1, "1")
[1] TRUE
```

(veryconfused) ok lol, I don't like this function :D

**Comment by IndrajeetPatil** [comment]
This behavior actually has nothing to do with this function and everything to do with implicit and arcane coercion rules of R

``` r
1 %in% "1"
#> [1] TRUE
```

<sup>Created on 2022-02-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by msevestre** [comment]
Lol. Arcane coercion rules..

I am going to name this the truth of the month. Respect @IndrajeetPatil

**Comment by IndrajeetPatil** [comment]
@PavelBal Is this what you want to do?

>  it cannot check whether e.g. a certain `DataSet` is inside a list of `DataSet`

```r
> library(ospsuite)
> library(ospsuite.utils)
> 
> # import observed data
> dataSet <- loadDataSetsFromExcel(
+   xlsFilePath = file.path(getwd(), "tests", "data", "CompiledDataSetStevens2012.xlsx"),
+   importerConfiguration = DataImporterConfiguration$new(file.path(getwd(), "tests", "data", "ImporterConfiguration.xml"))
+ )
> 
> isIncluded("Stevens_2012_placebo.Placebo_total", names(dataSet))
[1] TRUE
```

**Comment by PavelBal** [comment]
>  Is this what you want to do?

No, I meant that it must be documented that it only works on atomic data types. E.g. this would probably not work:

```
ds1 <- DataSet$new("DataSet1")
ds2 <- DataSet$new("DataSet1")
ds3 <- DataSet$new("DataSet1")

isIncluded(ds1, list(ds1, ds2, ds3))
```

And as already shown before - it does not work on lists:

```
> isIncluded(c(1,2,3), list(c(1,2,3)))
[1] FALSE
```

**Comment by PavelBal** [comment]
```
isIncluded(ds1, list(ds1, ds2, ds3))
#> Error in match(x, table, nomatch = 0L): 'match' requires vector arguments
isIncluded(c(ds1), list(ds1, ds2, ds3))
#> [1] TRUE
```

Sorry, but this just does not work. You cannot use e.g. R6 objects with this function.

```
> isIncluded(c(ds1), list(ds2))
[1] TRUE

> isIncluded(c(ds1), list(DataSet))
[1] TRUE
```

I am ok with this as long it is clear to the user ( == documented properly).

**Comment by PavelBal** [comment]
Re-opening it because the behavior is currently erroneous regarding non-primitive types

> So this function only works for primitive types basically.
Does it make sense to say that we throw an error if it is used with something else than char, int, double, boolean etc..?

Yes I would vote for this. This function has (hopefully) not been used with R6 classes or whatever, so let's not invest time unless we have a need for it.

BTW yes, `identical` is cool, I think we all should read the documentation for it and consider it in our code (especially in `if` statements).

```
> NA == NA
[1] NA
> identical(NA, NA)
[1] TRUE
```

Hell yeah, THIS makes sense!

**Comment by PavelBal** [comment]
@msevestre @IndrajeetPatil @pchelle

**Comment by IndrajeetPatil** [comment]
Haha

There is an entire book on the weird behaviour R sometimes exhibit:

![image](https://user-images.githubusercontent.com/11330453/152521105-f16042e4-be78-4e8a-bb02-e9525a0820f1.png)

**Comment by IndrajeetPatil** [comment]
To be fair to R though, it's not unique in this regard. Watch the notorious _WAT_ talk for a similar take on `JavaScript`:

https://www.youtube.com/watch?v=et8xNAc2ic8
