### ISSUE TITLE
'hasUniqueValues' 

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#31]
Documentation states 

`#' Remove duplicate values from data`

Either the docu is wrong (which I hope), or the function should be renamed.

Also the argument `data` does not make it clear that it requires a data frame. Wait, must it be a data frame? If not - wrong docu.

**Comment by PavelBal** [comment]
Do we really need this function at all?

**Comment by IndrajeetPatil** [comment]
> Do we really need this function at all?

I copy-pasted this from `OSPSuite.ReportingEngine` repo, so it's definitely needed there.

@pchelle, @abdullahhamadeh What do you think about the comments above?

**Comment by pchelle** [comment]
The documentation of the function is not correct (actually the function was not documented in `{ospsuite.reportingengine}`.
As the name suggests, this function only asserts that an array of values are all unique, thus it should return only `TRUE` if all values are unique and `FALSE` if they are not.

**Comment by pchelle** [comment]
Since it was only used internally, the argument `data` can be replaced by `values` or `x` or anything you see fit as input.

**Comment by pchelle** [comment]
Duplicate `NA` values are actually flagged as non unique:
```r
> hasUniqueValues(c("x", NA, "y", NA), na.rm=FALSE)
[1] FALSE
```
The argument `na.rm` is often used in R to remove `NA` values that could mess up the final result.
```r
> hasUniqueValues(c("x", NA, "y", NA), na.rm=TRUE)
[1] TRUE
```

**Comment by pchelle** [comment]
The function is necessary `{ospsuite.reportingengine}` because it assesses that workflows do not get duplicate input names for arguments that should be unique (such as pk parameters, simulations, etc.)

**Comment by IndrajeetPatil** [comment]
@pchelle Do you mind making a PR that updates the documentation to reflect all this thinking? 

I don't use this function, so hard for me to collect and put in writing these insights.

**Comment by PavelBal** [comment]
Ok, I think it is the name of the function that really confuses me. `hasUniqueValues` sounds like "does this data has unique values?", which is `TRUE` for e.g. `c(1, 2, 2, 3, 3)`, because the element `1` is unique.

For the questions "are all values of the data unique?", I would expect something like `isAllValuesUnique`.
@msevestre I would also like to hear your opinion.

**Comment by IndrajeetPatil** [comment]
Or, rather, `areAllValuesUnique` since there are possibly multiple values.

**Comment by PavelBal** [comment]
This must remain open as we did not really decide on the naming.

**Comment by IndrajeetPatil** [comment]
@msevestre Let us know what you think about these proposed, alternative names for this function.

**Comment by msevestre** [comment]
I agree the name is confusing
areAllValuesUnique is ok. Often we see Distinct
So areAllValuesDistinct

Or hasOnlyDistinctValues

Or allValuesAreDistinctIn 

Which reads like English...
if(allValuesAreDistinctIn(data))

**Comment by IndrajeetPatil** [comment]
I like `hasOnlyDistinctValues()`.
