### ISSUE TITLE
`formatNumerics`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#32]
`#' - If `object` is of type character or integer, `formatNumerics` leaves the values as is`

Why? Why should `formatNumerics(2L, scientific = TRUE)` return something else then `formatNumerics(2, scientific = TRUE)`?

**Comment by PavelBal** [comment]
Actually I think the output should ALWAYS be a string, no?

```
> formatNumerics(2)
[1] "2.00"
```

but 

```
> formatNumerics(2L, scientific = TRUE)
[1] 2
```

does not make any sense to me.

**Comment by PavelBal** [comment]
`#' @param digits Number of decimal digits to render`

I think the parameter should be rename to "decimalPlaces" or so. It first confused me because I though its to total number of digits...

**Comment by pchelle** [comment]
The idea of the function `formatNumerics` was to have a consistent wrapper that can account for `data.frame` variables because the R function `format` was not great in doing this job (different numeric columns were displaying different decimal places...).
Indeed, in `{ospsuite.reportingengine}`, the function is called to format the tables to include in the report in almost all cases. 
Such tables usually include a count, a population or N column that is an integer and nicer to display as is while the values get the user format.

**Comment by pchelle** [comment]
For inputs as simple as `2L`, you can still use the function `format` that will give you what you the formatting you want.

**Comment by pchelle** [comment]
Regarding `digits`, I kept a consistent name with the function `format` so that users would not be too confused, but I don't mind `decimalPlaces`

**Comment by PavelBal** [comment]
I am still not convinced why the function should return `character` for e.g. a `2` but a numeric for `2L`.

**Comment by msevestre** [comment]
>I am still not convinced why the function should return character for e.g. a 2 but a numeric for 2L.

I agree. This should be consistent returned type.

**Comment by PavelBal** [comment]
Now we have a `formatNumerics` in the Utils (which is an "extended" version from reporting engine?), but also such a function in `ospsuite`. Both behave differently and even have different signatures. This must be unified before using.

**Comment by msevestre** [comment]
the one is ospsuite should go. The one in utils should be used instead. RE should use this one also. 
@pchelle Why aren't we always returning a string?

**Comment by PavelBal** [comment]
And we should create an `ospsuiteUtilsEnv `or smth like this and store there the defaults for `digits`.

`ospsuiteEnv$formatNumericsSmall` is then obsolete and should be removed.

**Comment by msevestre** [comment]
`formatNumerics(2L, scientific = TRUE)`
should return 
`"2"`

as discussed with @pchelle

**Comment by IndrajeetPatil** [comment]
@pchelle Can you please file a PR with this change implemented? 

Please also include tests for the same so that we never regress to this behaviour again, even accidentally. Thanks.
