### ISSUE TITLE
`validateIsCharacter` 

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#33]
What for? It just duplicates `validateIsString`... And strictly speaking a character is only ONE character, so if we want to keep this function we should also check for length == 1.

@msevestre @IndrajeetPatil

**Comment by PavelBal** [comment]
Yes but why having two exact identical validate functions then?

**Comment by IndrajeetPatil** [comment]
> And strictly speaking a character is only ONE character

Not in R, no.

``` r
class("x")
#> [1] "character"
class("xyz")
#> [1] "character"
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

> Yes but why having two exact identical validate functions then?

Happy to remove `validateIsString()`, but that would cause a lot of breakage.

Note that these functions are aliases for each other. It's not like there is any code duplication going on.

**Comment by PavelBal** [comment]
`validateIsString()` is used a lot (ospsuite-r did not even have `validateIsCharacter`), so def. cannot remove it. Is `validateIsCharacter` used somewhere/a lot?

**Comment by msevestre** [comment]
I like win win situation. I think we should have named the method validateIsCharacter because we are in R. Aliasing is good. I would even suggest to move the impleentation to `validateIsCharacter` and have validateIsString use validateIsCharacter
