### ISSUE TITLE
checklist for CRAN submission

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#4]
add your TODOs here:

- [x] working github actions
- [x] more examples

**Comment by IndrajeetPatil** [comment]
@msevestre, @Yuri05, @PavelBal, @abdullahhamadeh, @pchelle 

I would like to get this package soon on CRAN, so please let me know if there are any other low-level helper functions that you think will be helpful to have in this utility package.

A list of current functions can be found here: https://www.open-systems-pharmacology.org/OSPSuite.RUtils/reference/index.html

**Comment by IndrajeetPatil** [comment]
Just to give you an idea of its scope, it will be the storage unit (or dumping ground? 😅) for general utility functions needed across the following R packages:

![image](https://user-images.githubusercontent.com/11330453/140944753-0986e145-e112-4d60-838b-32a040c238f6.png)

This way, we can make change only in one place, rather than in 2-3 different places.

**Comment by msevestre** [comment]
@pchelle I know you have made some changes to some of the methods in the reporting.engine package. Can you connect with @IndrajeetPatil to synchronize those changes?

**Comment by IndrajeetPatil** [comment]
@PavelBal I think the following functions from `{esqlabsR}` will be better suited in this package. Can I move them?

- [ ] `enumGetKey()`
- [ ] `enumPutList()`
- [ ] `validateFileExists()`
- [ ] `validateLength()`

**Comment by PavelBal** [comment]
@IndrajeetPatil `validateFileExists()` and `validateLength()`, but please make a separate PR so the others can review (and decide whether the functions should be included).

`enumGetKey()` and `enumPutList()` are just for backward compatibility with old esqlabs code, so no.

Also, I would prefer to remove mentioning of the `esqlabsR`. It is not really in the OSP ecosystem and I don't want to "promote" it as we cannot ensure any kind of support.

**Comment by IndrajeetPatil** [comment]
Got it! I have removed `{esqlabsR}` from README.

> please make a separate PR so the others can review

Will do

**Comment by IndrajeetPatil** [comment]
It's on CRAN! 🍾 

https://cran.r-project.org/web/packages/ospsuite.utils/index.html

**Comment by Yuri05** [comment]
nice!

**Comment by IndrajeetPatil** [comment]
We have crossed the 1000 download mark! 😅 

``` r
library(tidyverse)

cranlogs::cran_downloads(
  packages = "ospsuite.utils",
  from = "2021-12-08",
  to = Sys.Date()
) %>%
  tibble::as_tibble() %>%
  dplyr::summarise(total = sum(count))
#> # A tibble: 1 x 1
#>   total
#>   <dbl>
#> 1  1146

library(packageRank)

plot(
  cranDownloads("ospsuite.utils", from = "2021-12-08", to = Sys.Date()),
  smooth = TRUE,
  se = TRUE,
  r.version = TRUE
)
```

![](https://i.imgur.com/NUfZN4R.png)

<sup>Created on 2022-02-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by PavelBal** [comment]
Can only be from appveyor :D
