### ISSUE TITLE
Add .gitattribute specifying what we should use for line ending etc..

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.RUtils#41]
see https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/748

**Comment by msevestre** [comment]
Let's wait for the issue in ospsuite-R to be implemented and then we can duplicate

**Comment by IndrajeetPatil** [comment]
Cool.

**Comment by msevestre** [comment]
or we can implement here and if we are happy, we move it to the other repo

**Comment by IndrajeetPatil** [comment]
Have a look at my PR: https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/pull/40
