### ISSUE TITLE
Include parsing functions ?

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.RUtils#5]
I think the parsing functions `parseVariableToObject`, `parseVariableFromObject`, `parseValueToObject`  in tlf `aaa-utils.R` could be interesting in RUtils. 
However, they may create warnings in the packages that use them because they create only expressions (so the variable names are not captured by `devtools::check()`).

To illustrate their use, let's think of a function that modify fields of an R6 object or a list such as:
```
testFun <- function(r6,a,b,c){
r6$a <- a
r6$b <- b
r6$c <- c
}
```
which can be directly written as:
```
testFun <- function(r6,a,b,c){
eval(parseVariableToObject("r6", c("a", "b", "c")))
}
```

**Comment by IndrajeetPatil** [comment]
Will probably do this for the next release, if it is even possible.

**Comment by IndrajeetPatil** [comment]
After giving it some thought, I think these functions won't be of much utility outside the package where they are currently used.

So better for them to continue their lives in these namespaces.
