### ISSUE TITLE
What to do with all those warnings?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.RUtils#50]
![image](https://user-images.githubusercontent.com/1041237/152766380-0b3e9f8f-4c6b-4292-aae3-c708cf2bed95.png)

Should we check them out?

**Comment by msevestre** [comment]
"Check warning" they say.... :)

**Comment by IndrajeetPatil** [comment]
Ah, I see. 

Yeah, but that's GHA talking and we often need not concern ourselves with its warnings. The warnings we should care about are the ones in R CMD Check.  

At any rate, I will see if any of these lints are something we ought to be attending to or are false positives.

**Comment by msevestre** [comment]
Can we configure GHA to turn the warning off that we do not want to see / see as acceptable? Otherwise it's just noise

**Comment by IndrajeetPatil** [comment]
Yes, we can do that. 

Will file a PR soon.
