### ISSUE TITLE
Admin privileges for the maintainer

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#53]
@msevestre Can you please provide me admin privileges for this repo? 

I am not comfortable not having these privileges. As a maintainer, I don't want to be reliant on others in case I need to do any hot fixes, etc.

**Comment by msevestre** [comment]
Sure. I am just curious: What settings are you missing? You are maintainer of the project.... you should be able to do everything needed in case of a bug fix etc? No?
![image](https://user-images.githubusercontent.com/1041237/152966711-f56eb884-d718-4954-8095-fdb3cc9628d8.png)

**Comment by msevestre** [comment]
done

**Comment by IndrajeetPatil** [comment]
Thanks!

> What settings are you missing? 

For example, I couldn't merge my own approved PRs in the `develop` branch.

**Comment by msevestre** [comment]
>For example, I couldn't merge my own approved PRs in the develop branch.

This is due to the rule and not to the settings. Anything else?

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/152968671-4ef7f6d4-1a89-4756-8fac-e3836be31c63.png)

**Comment by IndrajeetPatil** [comment]
> This is due to the rule and not to the settings. 

That can't be the case. 
For example, we have the **same rule** for ospsuite-R package, and yet I could [merge my PR](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/760) without any approval.

**Comment by msevestre** [comment]
believe me

![image](https://user-images.githubusercontent.com/1041237/152970217-fa57d7c8-310c-4552-b08f-de8688fafe27.png)

**Comment by IndrajeetPatil** [comment]
Maybe `ospsuite` is a bad example, then. 

A better example would be `esqlabsR` package repo, which has the same rule. 

![image](https://user-images.githubusercontent.com/11330453/152989146-2f126e3d-7cc1-4aae-a04a-c7622ebce549.png)

But I can use my admin privileges to merge PR, approved or otherwise. 

![image](https://user-images.githubusercontent.com/11330453/152989602-511b0100-cd15-413b-bb61-65f750da9a31.png)

I couldn’t do this in the utilities package before you updated my privileges.

**Comment by msevestre** [comment]
of course. But the rule is not defined properly IMO. 
At any rate, you are admin
