### ISSUE TITLE
Add more messages from ospsuite-r

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.RUtils#67]

**Comment by PavelBal** [comment]
@msevestre @IndrajeetPatil 

I don't know how we are supposed to use the messages from the utils package. Do we export the `messages` list from the utils package? Do we re-export them in ospsuite? If we do not re-export - we always need to use the prefix `ospsuite.utils::messages$` instead of just `messages$`. I would be only OK with this if we move ALL messages to the utils package. This way, it will be consistent to ALWAYS use `ospsuite.utils::messages$` everywhere we need a message, otherwise it is sometimes with the prefix and sometimes without (when accessing the message stored in the package itself and not in utils...)

**Comment by IndrajeetPatil** [comment]
Closed in https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/commit/1f029a9f408095be4a286deeefe59195e68954f3
