### ISSUE TITLE
Add "checkIs..." methods

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.RUtils#7]
Is it also possible to add `checkIs...` methods similar to `validateIs...` but that would only throw a warning instead of an error in `error-checks.R` ? (not sure if prefix "check" is best suited here)

**Comment by IndrajeetPatil** [comment]
Do these functions already exist in `{tlf}` and can be moved, or do you mean to suggest that we can create new variants of the existing functions?

**Comment by pchelle** [comment]
There are already some of those in `{ospsuite.reportingengine}` such as `checkIsIncluded`.
I am also suggesting to create new variants if everyone think they can be useful

**Comment by IndrajeetPatil** [comment]
I think these are a bit too specific to be useful across the entire ecosystem, like the other helpers, so better to leave them in `{ospsuite.reportingengine}`.
