### ISSUE TITLE
Untested line of code

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#71]
The following line of code in `validateIsOfType()` function is not covered by any of our tests. 

https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/blob/1f029a9f408095be4a286deeefe59195e68954f3/R/validation-helpers.R#L46

Can anyone think of a context where this will be encountered?

**Comment by msevestre** [comment]
yep. Thanks @pchelle 
This is therefor tested with any test of validateIsCharacter? (unless this is only from console?)
