### ISSUE TITLE
Use `AppVeyor` to build binaries after each commit

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#76]
Just like in `{ospsuite}` package.

**Comment by IndrajeetPatil** [comment]
For _ospsuite_, the link is

https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip

For _ospsuite.utils_, something similar doesn't work:

https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-rutils/artifacts/ospsuite.utils.zip

Is it possible to make this happen?

**Comment by PavelBal** [comment]
We probably have to trigger the build of the package with the name `ospsuite.utils.zip`, without version number. Maybe take a look how it is done in AppVeyor of `ospsuite`?

**Comment by Yuri05** [comment]
In ospsuite we just manually create a copy of the package without the version number:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/8da4633c6e03b1a7f9b6d609cdd4f1e4f4606c73/appveyor.yml#L61
If you add the same here - should work

**Comment by IndrajeetPatil** [comment]
> In ospsuite we just manually create a copy of the package without the version number: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/8da4633c6e03b1a7f9b6d609cdd4f1e4f4606c73/appveyor.yml#L61 If you add the same here - should work

Tried this, but doesn't seem to work:
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-rutils/builds/43044129/artifacts

**Comment by Yuri05** [comment]
Because the pattern in the artifacts upload does not match the copied file.
https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/blob/7fbde4fd28419ce0f6583b8252ee309e8e14aba5/appveyor.yml#L81
Replace it with e.g. `ospsuite.utils*.zip`
