### ISSUE TITLE
List of utils functions

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite.RUtils#8]
Not sure if all that is below is useful. I suggested below a few util functions from `ospsuite.reportingengine` split by topics:
Math helpers
- `calculateResiduals` to calculate `y-x` or `log(y)-log(x)` (could be generalized to other formulas if needed)
- `calculateGMFE` to calculate the geometric mean fold error
- there could also be a function similar to `getPKRatioMeasure` from `tlf` that counts the number and ratio of observations within a range of values (e.g. `countValuesInRange(x, ymin, ymax)`)

Computation helpers
- `getAllowedCores` that gets the number of allowed CPU cores you can use for computation 

Printing helpers
- `formatNumerics` to print numeric values as characters using the appropriate number of digits and if with a scientific writing

**Comment by IndrajeetPatil** [comment]
If I run `getAllowedCores()`, I get nothing in return, and I am working on a Windows machine.
Are you sure this function works properly?

**Comment by IndrajeetPatil** [comment]
Can't include `formatNumerics()` because it relies on `ospsuiteEnv`, which I don't want to include in this package since it introduces a lot of other complexities.

```r
formatNumerics <- function(numerics, digits = ospsuiteEnv$formatNumericsDigits,
                           nsmall = ospsuiteEnv$formatNumericsSmall) {
  format(numerics, digits = digits, nsmall = nsmall)
}
```

**Comment by pchelle** [comment]
In the reporting engine, the function `format` was not consistent so I had written a different version without the `nsmall`.
Below is the `formatNumerics` I had in mind (or should we call it `renderNumerics` ?)

```r
#' @title formatNumerics
#' @description Render numeric values of an `object` using the specified format
#' @param object An R object such as a list, a data.frame, character or numeric values
#' If `object` is a data.frame or a list, `formatNumerics` applies on each of its fields
#' If `object` is of type character or integer, `formatNumerics` leaves the values as is
#' If `object` is of type numeric, `formatNumerics` applies the defined format
#' @param digits Number of decimal digits to render
#' @param scientific Logical value defining if scientific writing is rendered
#' @param return Numeric values are rendered as character values.
#' If `object` was a data.frame or a list, a data.frame or list is returned with numeric values rendered as character values.
#' @examples
#' # Format array of numeric values
#' formatNumerics(log(c(12, 15, 0.3)), digits = 1, scientific = TRUE)
#'
#' # Format a data.frame
#' x <- data.frame(parameter = c("a", "b", "c"), value = c(1, 110.4, 6.666))
#' formatNumerics(x, digits = 2, scientific = FALSE)
formatNumerics <- function(object, digits = 2, scientific = FALSE) {
validateIsInteger(digits)
validateIsLogical(scientific)

# Return integer as is before they are assumed as numeric
  if(is.integer(object)){
    return(object)
  }
# Method for numeric values
  if(is.numeric(object)){
    # Scientific writing: using isTRUE because logical NA can provoke crash in `if` loop
    if(isTRUE(scientific)){
      return(sprintf(paste0('%.', object, 'e'), value))
    }
    # Decimal writing
    return(sprintf(paste0('%.', object, 'f'), value))
  }
# Method for data.frame or list: update each of its fields
  if(isOfType(object, c("list", "data.frame"))){
    for(field in 1:length(object)){
      object[[field]] <- formatNumerics(object[[field]], digits, scientific)
    }
  }
  # For other types such as character return values as is
  return(object)
}
```

Would it work if the default parameters are kept independent from the package here (as above) and then OSP packages wrap the function with their inner default values ?
E.g. 
```r 
formatNumerics <- function(numerics, digits = ospsuiteEnv$formatNumericsDigits, scientific = ospsuiteEnv$formatNumericsScientific) {
  formatNumerics(object = numerics, digits = digits, scientific = scientific )
}
```

**Comment by IndrajeetPatil** [comment]
Yes, that sounds like the perfect solution! Thanks.

**Comment by IndrajeetPatil** [comment]
In the function you have written above `value` inside function body should instead be `object`, correct?

Also, is it actually working as expected? This is what I see if I run the examples you shared:

``` r
library(ospsuite.utils)

formatNumerics(log(c(12, 15, 0.3)), digits = 1, scientific = TRUE)
#> [1] "" "" ""

x <- data.frame(parameter = c("a", "b", "c"), value = c(1, 110.4, 6.666))
formatNumerics(x, digits = 2, scientific = FALSE)
#>   parameter
#> 1         a
#> 2         b
#> 3         c
#>                                                                                                                 value
#> 1                                                                                                                 1.0
#> 2 1232.12121212121212121212122000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
#> 3
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pchelle** [comment]
> In the function you have written above `value` inside function body should instead be `object`, correct?
> 
> Also, is it actually working as expected? This is what I see if I run the examples you shared:
> 
> ```r
> library(ospsuite.utils)
> 
> formatNumerics(log(c(12, 15, 0.3)), digits = 1, scientific = TRUE)
> #> [1] "" "" ""
> 
> x <- data.frame(parameter = c("a", "b", "c"), value = c(1, 110.4, 6.666))
> formatNumerics(x, digits = 2, scientific = FALSE)
> #>   parameter
> #> 1         a
> #> 2         b
> #> 3         c
> #>                                                                                                                 value
> #> 1                                                                                                                 1.0
> #> 2 1232.12121212121212121212122000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> #> 3
> ```
> 
> Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

My bad, originally it was called `value` but `object` made more sense. I should have tested the updated version first.
```r
# Scientific writing: using isTRUE because logical NA can provoke crash in `if` loop
    if(isTRUE(scientific)){
      return(sprintf(paste0('%.', digits, 'e'), object))
    }
    # Decimal writing
    return(sprintf(paste0('%.', digits, 'f'), object))
```

**Comment by IndrajeetPatil** [comment]
Thanks, that fixed it.

> there could also be a function similar to getPKRatioMeasure from tlf that counts the number and ratio of observations within a range of values (e.g. countValuesInRange(x, ymin, ymax))

I think this will be  a bit more complicated since it relies on the `PKRatioDataMapping` object, and so we will also need to include it, and so on and so forth.

**Comment by IndrajeetPatil** [comment]
Calculate functions need `ResidualScales` enum, and so they are also not ideal candidates for inclusion here.
