### ISSUE TITLE
Move `validateVectorDepth()` here?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#80]
The only issue is _ospsuite.utils_ will gain _purrr_ as a dependency.

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e85444e9105500dcb962a3401bba7bdf9f8a6263/R/utilities-data-combined.R#L165-L199

**Comment by PavelBal** [comment]
I don't know where you use this function, but I am against exporting it because I actually do not agree with the statement "a list with depth >2 is not a valid list", and this is exactly what this function states.

**Comment by IndrajeetPatil** [comment]
> "a list with depth >2 is not a valid list",

Can you show me where that statement appears?

The function is checking vector depths for lists which are passed as arguments, and you rarely need a nested list. We don't allow nested lists anywhere.

```
#' Function parameters that accept a vector argument, the vector with depth
#' greater than 2, which corresponds to a nested list, is rarely desirable.
#'
#' The `isVectorDepth()` checks if the vector is of desirable depth, while
#' `validateVectorDepth()` validates the same.
```

**Comment by IndrajeetPatil** [comment]
This whole validation becomes irrelevant in the new API (https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/853), so closing this.
