### ISSUE TITLE
Why is the release already created ?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.RUtils#83]
![image](https://user-images.githubusercontent.com/1041237/156583184-92c241a6-cd09-4771-b772-4d4c60d66d5e.png)

It should probably be created once we merge on main...

**Comment by IndrajeetPatil** [comment]
I wanted the GitHub release to have the same date as the CRAN release date. 

The attached binaries are from CRAN 1.2.0 release. I am not sure about the source code, though.

**Comment by msevestre** [comment]
>I wanted the GitHub release to have the same date as the CRAN release date

Hum...I don't think we should care about this. 
IMO, We should create a tag version of main , and THEN release to CRAN? Don't you think?

**Comment by IndrajeetPatil** [comment]
> We should create a tag version of main , and THEN release to CRAN

Sure, that souds good to me.

As far as `OSP`'s R ecosystem goes, we are in a bit of _terra nova_ when it comes to CRAN submissions, so I am still figuring my way about it.

I will add this to our coding standards as well so that we have this in writing.

**Comment by msevestre** [comment]
>But does NUGET ever reject packages?

nope. ok so let's think about this a bit

**Comment by IndrajeetPatil** [comment]
Any further thoughts on this? 

I want to `1.3.0` version to CRAN for a new release as soon as all the pending PRs are merged.

**Comment by IndrajeetPatil** [comment]
There needs to be a new release for version 1.3.0.

I will archive the package on CRAN, so we can forget about this whole discussion and follow release conventions adopted in other ways packages.

**Comment by IndrajeetPatil** [comment]
Closing in favour of https://github.com/Open-Systems-Pharmacology/OSPSuite.RUtils/issues/109
