### ISSUE TITLE
bug in `validateIsInteger()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite.RUtils#9]
@pchelle, @msevestre This is a bug, correct? 

``` r
library(ospsuite.utils)

typeof(5L)
#> [1] "integer"

validateIsInteger(5L)
#> Error in validateIsInteger(5L): tryCatch: argument '5L' is of type 'integer', but expected 'integer'!
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
I am confused about whether this is a bug or not because the function is clearly successfully being used in packages, and so I am not sure if this is the expected behavior from it.

**Comment by msevestre** [comment]
Clearly a bug.
But 5L...what does that mean?

**Comment by IndrajeetPatil** [comment]
Numeric suffix to explicitly define the type of literal.

It's actually inspired by C++/C#, where `5L` will convert it to a `long int`.

**Comment by msevestre** [comment]
And I thought R did not differentiate between int and long. Everything was numeric :). Well I was wrong.

**Comment by msevestre** [comment]
WE are doing some weird shit to check if a number is an integer. Maybe we should just check if typeof() is Integer  lol

**Comment by IndrajeetPatil** [comment]
lol, yes

We should take advantage of base-R's` is.*()` functions: For example,

``` r
is.integer(5L)
#> [1] TRUE
is.double(1.1)
#> [1] TRUE
is.character("x")
#> [1] TRUE
is.logical(TRUE)
#> [1] TRUE
```

<sup>Created on 2021-11-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
